Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name for identifying resources by prefixing in name key
  # NodeRoleArn:
  #   Type: String
  #   Description: node role arn

Resources:
  eksNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: firstClusterTesting
      DiskSize: 30
      InstanceTypes:
        - t2.medium
      NodegroupName: firstNodeGroupTesting
      NodeRole:
        arn:aws:iam::909937860942:role/test12-nodeRole-1DEKBC1Z2XH9M
        # - Fn::ImportValue: !Sub "${EnvironmentName}-nodeRole"
      ScalingConfig:
        DesiredSize: 1
        MaxSize: 2
        MinSize: 1
      Subnets:
        - Fn::ImportValue: !Sub "${EnvironmentName}-PVT-SUB-01"
